In [7]:
import pandas as pd
import numpy as np
import folium

In [3]:
speedLimits_df = pd.read_csv("Speed_Limits.csv")
cameraLocations_df = pd.read_csv("Traffic_Camera_Locations.csv")
incidents_df = pd.read_csv("Traffic_Incidents.csv")
signals_df = pd.read_csv("Traffic_Signals.csv")
signs_df = pd.read_csv("Traffic_Signs.csv")
volumes_df = pd.read_csv("Traffic_Volumes_for_2018.csv")
display(speedLimits_df,cameraLocations_df,incidents_df,signals_df,signs_df,volumes_df)

,BOUND,CREATED_DT,DISTANCE,SPEED,STREET_NAME,multiline
0,N,NaN,0.81,60,MILLSIDE BV SE,MULTILINESTRING ((-114.073657541927 50.9135772...
1,NaN,2018/10/30,NaN,40,DEERFOOT TR SE RAMP,MULTILINESTRING ((-114.034764352652 50.9962241...
2,S,2018/10/23,NaN,60,HARVEST HILLS BV N,MULTILINESTRING ((-114.068566084381 51.1667137...
3,N,2019/10/09,4.37,70,CROWCHILD TR SW,MULTILINESTRING ((-114.117825190175 51.0050022...
4,NaN,2018/10/30,NaN,80,STONEY TR NE RAMP,MULTILINESTRING ((-113.918850808952 51.0624482...
...,...,...,...,...,...,...
1447,S,2018/10/29,NaN,80,STONEY TR NW,MULTILINESTRING ((-114.233241861102 51.0915352...
1448,N/S,2018/10/31,NaN,70,37 ST SW,MULTILINESTRING ((-114.140309947853 50.9177590...
1449,W,2018/11/02,NaN,60,SUN VALLEY BV SE,MULTILINESTRING ((-114.030210417675 50.9043134...
1450,E,NaN,1.85,60,JOHN LAURIE BV,MULTILINESTRING ((-114.177870798005 51.1241752...
1451,NaN,2018/12/06,NaN,60,STONEY TR SE RAMP,MULTILINESTRING ((-113.988645145196 50.8984752...

,Camera Location,Quadrant,Camera URL,longitude,latitude
0,Stoney Trail / Deerfoot Trail SE,SE,http://trafficcam.calgary.ca/loc86.jpg,-113.976606,50.900726
1,Memorial Drive / 52 Street E,NE,http://trafficcam.calgary.ca/loc3.jpg,-113.955818,51.053253
2,Crowchild Trail / Shaganappi Trail NW,NW,http://trafficcam.calgary.ca/loc37.jpg,-114.149379,51.098849
3,Crowchild Trail / Sarcee Trail NW,NW,http://trafficcam.calgary.ca/loc126.jpg,-114.178204,51.111255
4,Airport Trail / Barlow Trail NE,NE,http://trafficcam.calgary.ca/loc114.jpg,-114.001451,51.139352
...,...,...,...,...,...
121,Memorial Drive / Edmonton Trail NE,NE,http://trafficcam.calgary.ca/loc30.jpg,-114.050136,51.050802
122,Glenmore Trail / Barlow Trail SE,SE,http://trafficcam.calgary.ca/loc98.jpg,-113.981495,50.979446
123,Glenmore Trail / Stoney Trail SE,SE,http://trafficcam.calgary.ca/loc128.jpg,-113.929263,50.979635
124,5 Avenue / 5 Street SW,SW,http://trafficcam.calgary.ca/loc122.jpg,-114.073644,51.048677
125,9 Avenue / 3 Street SE,SE,http://trafficcam.calgary.ca/loc91.jpg,-114.055664,51.044390

,INCIDENT INFO,DESCRIPTION,START_DT,MODIFIED_DT,QUADRANT,Longitude,Latitude,location,Count,id
0,Westbound McKnight Boulevard approaching John ...,2 vehicle incident.,12/09/2016 04:46:32 PM,12/09/2016 05:16:54 PM,NW,-114.083318,51.097316,"(51.09731625733, -114.083317961464)",1,2016-12-09T16:46:3251.0973162573297-114.083317...
1,20 Avenue at 8 Street NW,2 vehicle incident.,12/09/2016 04:58:23 PM,12/09/2016 05:16:54 PM,NW,-114.081378,51.070539,"(51.070538552637, -114.081377719156)",1,2016-12-09T16:58:2351.0705385526371-114.081377...
2,Sunridge Way at 36 Street NE,There is an incident involving LRT.,12/09/2016 05:14:08 PM,12/09/2016 05:16:54 PM,NE,-113.984934,51.067299,"(51.067298691023, -113.98493374196)",1,2016-12-09T17:14:0851.0672986910231-113.984933...
3,Westbound Stoney approaching Shaganappi Trail NW.,Multi vehicle incident.,12/09/2016 05:16:08 PM,12/09/2016 05:16:53 PM,NW,-114.147933,51.152736,"(51.152736445625, -114.147933369876)",1,2016-12-09T17:16:0851.1527364456253-114.147933...
4,Southbound Nose Hill Drive approaching Crowchi...,Multi vehicle incident.,12/09/2016 05:38:05 PM,12/09/2016 05:55:52 PM,NW,-114.203241,51.119684,"(51.11968378497, -114.203240843777)",1,2016-12-09T17:38:0551.1196837849704-114.203240...
...,...,...,...,...,...,...,...,...,...,...
19783,Southbound Deerfoot Trail and Douglasdale Bou...,Multi-vehicle incident. Blocking the right lane,07/11/2020 07:21:57 PM,NaN,NaN,-114.005304,50.946741,"(50.94674131426537, -114.00530375385111)",1,2020-07-11T19:21:5750.94674131426537-114.00530...
19784,Shawnessy Boulevard and Shawville Boulevard SE,Two vehicle incident. Blocking multiple lanes.,07/11/2020 10:29:09 PM,NaN,NaN,-114.069753,50.912974,"(50.91297382324482, -114.06975311526708)",1,2020-07-11T22:29:0950.91297382324482-114.06975...
19785,Eastbound Stoney Trail after Shaganappi Trail...,Traffic incident.,07/11/2020 11:26:45 PM,NaN,NaN,-114.150728,51.152731,"(51.15273080944574, -114.15072838091025)",1,2020-07-11T23:26:4551.15273080944574-114.15072...
19786,Symons Valley Road NW and 144 Avenue NW,Traffic incident. The road is closed between ...,07/12/2020 08:34:16 AM,NaN,NaN,-114.134978,51.183220,"(51.18321993655643, -114.13497799337898)",1,2020-07-12T08:34:1651.18321993655643-114.13497...
19787,Eastbound Memorial Drive and Deerfoot Trail SE,Multi-vehicle incident. Blocking the right lane,07/12/2020 03:52:21 PM,NaN,NaN,-114.019418,51.047762,"(51.047761513729455, -114.01941796567567)",1,2020-07-12T15:52:2151.047761513729455-114.0194...

,INSTDATE,FIRSTROAD,SECONDROAD,QUADRANT,INT_TYPE,PEDBUTTONS,PED_TIMER,ACCESSIBLE PEDESTRIAN SIGNAL,latitude,longitude,Point,Count
0,1969/04/01,KENSINGTON ROAD,12 STREET,NW,Overhead Flasher,Yes,No,NaN,51.052514,-114.091740,POINT (-114.091739730382 51.052513524679),1
1,2005/02/09,COUNTRY HILLS BOULEVARD,COVENTRY HILLS BOULEVARD,NE,Traffic signal T intersection,Yes,No,NaN,51.154211,-114.052475,POINT (-114.05247454616 51.154210611434),1
2,2000/11/13,McCALL WAY,PEGASUS ROAD,NE,Traffic signal,Yes,No,NaN,51.094081,-114.011478,POINT (-114.011477743314 51.094081325343),1
3,1973/01/01,72 AVENUE,CENTRE STREET,N,Traffic signal,Yes,No,NaN,51.117992,-114.069588,POINT (-114.069587594341 51.11799160169),1
4,1957/01/01,9 AVENUE,15 STREET/17 AVENUE,SE,Traffic signal,Yes,No,NaN,51.037739,-114.025122,POINT (-114.025122275833 51.037738985756),1
...,...,...,...,...,...,...,...,...,...,...,...,...
1533,2017/08/03,COUNTRY HILLS BOULEVARD,ROCKY RIDGE RECREATIONAL FACILITY,NW,Traffic signal T intersection,Yes,No,NaN,51.154147,-114.228956,POINT (-114.228956047964 51.15414689593),1
1534,2017/04/12,BRIDLERIDGE WAY,BRIDLEWOOD ROAD,SW,Pedestrian RRFB,Yes,No,NaN,50.902069,-114.109199,POINT (-114.109199438382 50.902068514229),1
1535,1966/08/01,10 STREET,23 AVENUE,NW,Overhead Flasher,Yes,No,NaN,51.073213,-114.084589,POINT (-114.084588882838 51.073213223999),1
1536,1956/01/01,5 AVENUE,1 STREET,SE,Traffic signal,No,Yes,NaN,51.048341,-114.060387,POINT (-114.060387455583 51.048340950291),1
1537,2017/08/11,SUN VALLEY BOULEVARD,SUNPARK GATE,SE,Traffic signal,Yes,Yes,NaN,50.906049,-114.058065,POINT (-114.058064969258 50.90604877345),1

,BLADE_TYPE,COMMENTS,FACING_CD,FLD_SRC_TXT,INSTDATE,MATERIAL,PL_TY,REUSE,SGN_COUNT_NO,SGN_STA_CD,...,STA_CD,SIZE_CD,SUPPORTTYPE,UNITID,TE_SIGNLOCATION_UNITID,POINT,Ward Boundaries,City Quadrants,Calgary Communities,Ward Boundaries 2013-2017
0,Regulatory,NaN,N,NaN,2007/07/01,NaN,NaN,NaN,1.0,A,...,A,60X75,NaN,1.109184e+09,1109082667,POINT (-114.210957448601 51.0685668243),1.0,1.0,128.0,14.0
1,Parking Restrictions,NaN,W,GPS,2016/08/18,High Intensity,SG_40-06,NaN,0.0,R,...,R,30X30,Signpole,1.110021e+09,1110021182,POINT (-113.935804152861 50.911165903496),4.0,3.0,96.0,8.0
2,Timed Parking,NaN,NE,Field Estimate,NaN,NaN,SG_40-05,NaN,4.0,A,...,R,SPECIAL,Signpole,1.110202e+09,1109526373,POINT (-114.05423120852 51.042027593481),14.0,3.0,260.0,5.0
3,Timed Parking,NaN,NE,Field Estimate,2019/01/16,High Intensity,SG_40-05,NaN,4.0,A,...,A,SPECIAL,Signpole,1.110202e+09,1109286994,POINT (-114.053597489366 51.04135079758),14.0,3.0,260.0,5.0
4,Warning,NaN,W,Field Estimate,2018/09/12,High Intensity,SG_40-57,NaN,0.0,A,...,A,NaN,Signpole,1.110271e+09,1110172249,POINT (-113.935926247512 50.911341384981),4.0,3.0,96.0,8.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
207515,Street Name,NaN,E,GPS,2005/07/01,High Intensity,NaN,NaN,1.0,A,...,A,30XL,Trunk,1.109144e+09,1109076036,POINT (-114.089566544877 50.91413523827),5.0,1.0,156.0,6.0
207516,Regulatory,NaN,N,Field Estimate,2015/06/10,High Intensity,SG_40-05,NaN,3.0,A,...,A,SPECIAL,Signpole,1.109942e+09,1109941864,POINT (-114.073475226496 51.050465695905),14.0,1.0,262.0,2.0
207517,Parking Restrictions,NaN,SW,Field Estimate,2008/07/03,NaN,SG_40-06,NaN,3.0,A,...,A,30X45,Signpole,1.109276e+09,1109276231,POINT (-114.090109343345 51.052801038311),7.0,2.0,40.0,7.0
207518,Street Name,NaN,NW/SE,GPS,2004/07/01,High Intensity,SG_40-99,NaN,2.0,A,...,A,15XL,Signpole,1.109230e+09,1109092275,POINT (-114.053874443342 50.974157960171),10.0,3.0,174.0,5.0
207519,Parking Restrictions,NaN,NE,NaN,1991/07/02,High Intensity,SG_40-06,NaN,1.0,A,...,A,30X30,Signpole,1.109195e+09,1109049565,POINT (-114.006688140223 51.073240858843),9.0,4.0,106.0,3.0

,YEAR,SECNAME,Shape_Leng,VOLUME,multilinestring
0,2018,5AVS12,172.570274,22000,MULTILINESTRING ((-114.06036700906716 51.04831...
1,2018,94AVSEWBON,189.451491,5000,MULTILINESTRING ((-114.06876825342002 50.96863...
2,2018,12STNE29,261.453939,5000,MULTILINESTRING ((-114.03372206187294 51.05323...
3,2018,100AVNE1,804.353006,2000,MULTILINESTRING ((-114.01318801277267 51.14336...
4,2018,106AVSE1,507.320869,14000,MULTILINESTRING ((-113.98128756128924 50.95784...
...,...,...,...,...,...
1764,2018,CNTRYHILLS9DEERFT,715.577099,44000,MULTILINESTRING ((-114.02797586216911 51.15420...
1765,2018,BARLOW13SGLEN,797.555381,27000,MULTILINESTRING ((-113.98198296908507 50.97234...
1766,2018,19STNE1B2,184.577040,20000,MULTILINESTRING ((-114.01338212545333 51.06538...
1767,2018,WALDNGASE,139.327583,7000,MULTILINESTRING ((-114.03567148851693 50.87574...
1768,2018,WALDNGASEB,147.084816,12000,MULTILINESTRING ((-114.03570421043062 50.87578...

In [60]:
boundaries_df = pd.read_csv("City_Boundary_layer.csv")
data = boundaries_df['the_geom'].array[0].split('((')  # split the data on the double opening brackets so the first entry becomes 'POLYGON '
data = data[1].strip('))')  # data becomes the data excluding 'POLYGON ' and the double closing brackets at the end are removed
data = data.split(',')  # data gets split on commas
for i in range(len(data)):
    data[i] = data[i].split(' ')
    
boundaries_df['longitude'] = ''
boundaries_df['latitude'] = ''
boundaries_df = boundaries_df.append({'longitude': data[0][0],'latitude': data[0][1]},ignore_index=True)
for i in range(1,len(data)):
    boundaries_df = boundaries_df.append({'longitude': data[i][1],'latitude': data[i][2]},ignore_index=True)
boundaries_df = boundaries_df[1:]  # get rid of the empty first row
boundaries_df = boundaries_df[['latitude','longitude']]  # get rid of extraneous columns
east_bound = float(boundaries_df['longitude'].min())   # east boundary is the minimum longitude
west_bound = float(boundaries_df['longitude'].max())   # west boundary is the maximum longitude
north_bound = float(boundaries_df['latitude'].max())   # north boundary is the maximum latitude
south_bound = float(boundaries_df['latitude'].min())   # south boundary is the minimum latitude
boundaries_df.to_csv(r"C:\Users\Pozzy\Desktop\Master's\Summer Semester\ENSF 592\Project\Project\Phase II\ENSF592-ProjectPhase2\df_boundaries.csv")

In [61]:
# print(boundaries_df)
print("West bound: ",west_bound)
print("East bound: ",east_bound)
print("North bound: ",north_bound)
print("South bound: ",south_bound)

West bound:  -114.315796
East bound:  -113.859905
North bound:  51.212425
South bound:  50.842822

In [157]:
boundaries_df.latitude = boundaries_df.latitude.astype(float)
boundaries_df.longitude = boundaries_df.longitude.astype(float)
# boundaries_df
boundaries_df['latitude_bins'] = pd.cut(boundaries_df['latitude'],bins=10)#,labels=[10,9,8,7,6,5,4,3,2,1]
boundaries_df['longitude_bins'] = pd.cut(boundaries_df['longitude'],bins=10)#,labels=[1,2,3,4,5,6,7,8,9,10]
# pd.set_option('display.max_rows',None)
# boundaries_df.sort_values(['longitude'])

In [164]:
def hello():
    return 'hello'

m = folium.Map(location=[51.05011, -114.08529], zoom_start=10)
folium.Rectangle(bounds=[[north_bound,west_bound],[south_bound,east_bound]],color='#ff7800', fill=True, fill_color='#ffff00', fill_opacity=0.2).add_to(m)
# display(m)
latitude_bins_list = boundaries_df['latitude_bins'].unique()
longitude_bins_list = boundaries_df['longitude_bins'].unique()
longitude_bins_list = longitude_bins_list.sort_values()
# print(len(longitude_bins_list))
# print(latitude_bins_list)
for i in range(len(latitude_bins_list)-1):
    for j in range(len(latitude_bins_list)-1):
        folium.Rectangle(bounds=[[float(latitude_bins_list[i].right),float(longitude_bins_list[j].left)],
                                [float(latitude_bins_list[i+1].right),float(longitude_bins_list[j+1].left)]],
                        color='#2B2A2A', fill=True, fill_color="#706565",fill_opacity=0.1,event=on(type='click', 
                                                                fn='hello')).add_to(m)
        if j == 8:
            folium.Rectangle(bounds=[[float(latitude_bins_list[i].right),float(longitude_bins_list[9].left)],
                                    [float(latitude_bins_list[i].left),float(longitude_bins_list[9].right)]],
                            color='#2B2A2A', fill=True, fill_color="#706565",fill_opacity=0.1).add_to(m)
        if i == 8:
            folium.Rectangle(bounds=[[float(latitude_bins_list[9].right),float(longitude_bins_list[j].left)],
                                    [float(latitude_bins_list[9].left),float(longitude_bins_list[j].right)]],
                            color='#2B2A2A', fill=True, fill_color="#706565",fill_opacity=0.1).add_to(m)
folium.Rectangle(bounds=[[float(latitude_bins_list[9].right),float(longitude_bins_list[9].left)],
                        [float(latitude_bins_list[9].left),float(longitude_bins_list[9].right)]],
                color='#2B2A2A', fill=True, fill_color="#706565",fill_opacity=0.1).add_to(m)
display(m)

NameError: name 'on' is not defined

In [152]:
print(longitude_bins_list)
print(latitude_bins_list)

[(-114.316, -114.27], (-114.27, -114.225], (-114.225, -114.179], (-114.179, -114.133], (-114.133, -114.088], (-114.088, -114.042], (-114.042, -113.997], (-113.997, -113.951], (-113.951, -113.905], (-113.905, -113.86]]
Categories (10, interval[float64]): [(-114.316, -114.27] < (-114.27, -114.225] < (-114.225, -114.179] < (-114.179, -114.133] ... (-114.042, -113.997] < (-113.997, -113.951] < (-113.951, -113.905] < (-113.905, -113.86]]
[(51.175, 51.212], (51.139, 51.175], (51.102, 51.139], (51.065, 51.102], (51.028, 51.065], (50.991, 51.028], (50.954, 50.991], (50.917, 50.954], (50.88, 50.917], (50.842, 50.88]]
Categories (10, interval[float64]): [(50.842, 50.88] < (50.88, 50.917] < (50.917, 50.954] < (50.954, 50.991] ... (51.065, 51.102] < (51.102, 51.139] < (51.139, 51.175] < (51.175, 51.212]]